### PR TITLE
Add `repair`

### PR DESCRIPTION
**Pull request by Mwalters75**
Repairs or updates MeltOS.

### CODE REVIEW

**Review by Melt2002 — COMMENTED** [review]
Please send a screenshot(s) or video of you testing this out.

**Comment by Mwalters75** [comment]
image

**Comment by Melt2002** [comment]
That screenshot shows an error saying curl could not fetch the file.

**Comment by Melt2002** [comment]
image

**Comment by Mwalters75** [comment]
> image

Actually, it's this error, but I don't think it's a error at all, because it works when updating:
image

**Comment by Melt2002** [comment]
> > image
> 
> Actually, it's this error, but I don't think it's a error at all, because it works when updating: image

No, that's an error that means downloading didn't work.

**Comment by Mwalters75** [comment]
OK, I fixed the error.

**Review by Melt2002 — APPROVED** [review]

**Pull request merged**
